apiVersion: v1
kind: Service
metadata:
  name: {{.Values.services.centralize_port}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: centralize-api
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080