apiVersion: v1
kind: Secret
metadata:
  name: mysql-credential
  namespace: {{.Values.namespace}}
data:
  MasterData: {{.Values.connection_strings.master_data | b64enc | quote}}
  Identity: {{.Values.connection_strings.identity | b64enc | quote}}
  Orchestration: {{.Values.connection_strings.orchestration | b64enc | quote}}
  Notification: {{.Values.connection_strings.notification | b64enc | quote}}
  Workspace: {{.Values.connection_strings.workspace | b64enc | quote}}
type: Opaque
